name: market_scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas yfinance

      - name: Run Stock Script
        run: python get_stocks.py

      - name: Write to Google Sheets
        uses: jroehl/gsheet.action@v1.0.0
        with:
          spreadsheetId: ${{ secrets.SPREADSHEET_ID }}
          commands: |
            [
              {
                "command": "update",
                "args": {
                  "worksheet": "Raw Data",
                  "data": "MarketData_Pro.csv",
                  "minCol": 1
                }
              }
            ]
